#!/bin/bash

set -eu

# It seems alpine is broken about /proc.
#       non i64 value found: [key=VmLib, val=18446744073709551452] (path=/proc/self/status) (Exception)

make test/0.33.0
make test/0.33.0 TARGET=spec_ext CFLAGS="--warnings=none"
make test/0.35.1
make test/0.35.1 TARGET=spec_ext CFLAGS="--warnings=none"
make test/0.36.1
make test/1.0.0
make test/1.1.1
make test/1.8.2
