# Load individually because of dependencies and usage conditions.

require "./pretty/time" # Pretty::Time.now is special

require "./pretty/ansi"
require "./pretty/bar"
require "./pretty/bytes"
require "./pretty/colorize"
require "./pretty/crontab"
require "./pretty/crystal"
require "./pretty/date"
require "./pretty/df"
require "./pretty/diff"
require "./pretty/dir"
require "./pretty/error"
require "./pretty/file"
require "./pretty/json"
require "./pretty/lines"
require "./pretty/logger"
require "./pretty/mem_info"
require "./pretty/method"
require "./pretty/number"
require "./pretty/periodical"
require "./pretty/process_info"
require "./pretty/stopwatch"
require "./pretty/string"
require "./pretty/time"
require "./pretty/truncate"
require "./pretty/uri"
require "./pretty/used_memory"
require "./pretty/version"
